# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Selfie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Selfie
  pod 'SDCycleScrollView','~> 1.64'
  pod 'UIView+draggable'
  target 'SelfieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
